### ISSUE TITLE
Re-wiring output connection causes the pin to disappear

### ISSUE THREAD

**Issue by ajenyon** [PrismPipeline/QuiltiX#27] opened 2023-08-28 18:02 UTC
To re-produce:

Create a sub-graph with at least one connection to an 'outputs' node
![image](https://github.com/PrismPipeline/QuiltiX/assets/33992322/48a57b8b-acf7-48b8-bf7b-46e760bc9346)

Drag a connection from another node to the same pin
![image](https://github.com/PrismPipeline/QuiltiX/assets/33992322/2a087459-cac0-4829-9804-f1123bfc6896)

Expected behaviour:
The connection is replaced, and the output pin (including its name) is preserved

Actual behavior:
The pin disappears, meaning it needs to be re-created and named from scratch

**Comment by melMass** [comment] 2023-08-30 18:41
This is a duplicate of #24

**Comment by manuelkoester** [comment] 2023-09-04 10:34
Hey ajenyon!

Thanks for this. I will keep this open as this is for the outputs node of nodegraph and might be slightly different from #24

**Comment by manuelkoester** [comment] 2024-06-21 17:32
The only thing remaining to fix this is to now also match the data type to the new connection.

**Closed** 2024-07-05 15:08 UTC
Labels: bug
